#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

current_branch=$(git branch --show-current)
if [ "$current_branch" = "main" ]; then
    echo "Direct commits to the main branch are not allowed."
    exit 1
fi
